name: Build Android apk

on:
  workflow_dispatch:
    inputs:
      comments:
        description: 'Comments'
        required: true
        default: 'Manual build Actions'

  push:
    branches:
      - test-develop

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Getting the repo
        uses: actions/checkout@v2
      - name: Installing Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install React Native CLI
        run: |
          yarn global add react-native-cli
      - name: Install yarn dependencies
        run: |
          yarn install
      - name: Create config.js file
        run: |
            cp ./config/config.sample.js ./config/config.js
      - name: Building bundle
        run: |
          yarn react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

